export const SET_USER = 'SET_USER';
export const SET_CURRENT_TAB = 'SET_CURRENT_TAB';
export const SET_LOGIN_VALIDITY = 'SET_LOGIN_VALIDITY';
export const SET_PLAYING_SONG = 'SET_PLAYING_SONG';
export const SET_PLAYING_PLAYLIST = 'SET_PLAYING_PLAYLIST';
export const SET_SEARCH_TEXT = 'SET_SEARCH_TEXT';
export const SET_SEARCH_TEXT = 'SET_SEARCH_TEXT';

export const FETCH_ALL_PLAYLISTS_PENDING = 'FETCH_ALL_PLAYLISTS_PENDING';
export const FETCH_ALL_PLAYLISTS_SUCCESS = 'FETCH_ALL_PLAYLISTS_SUCCESS';
export const FETCH_ALL_PLAYLISTS_ERROR = 'FETCH_ALL_PLAYLISTS_ERROR';

export const FETCH_PLAYLIST_PENDING = 'FETCH_PLAYLIST_PENDING';
export const FETCH_PLAYLIST_SUCCESS = 'FETCH_PLAYLIST_SUCCESS';
export const FETCH_PLAYLIST_ERROR = 'FETCH_PLAYLIST_ERROR';

export const FETCH_MINISONGSEARCH_PENDING = 'FETCH_MINISONGSEARCH_PENDING';
export const FETCH_MINISONGSEARCH_SUCCESS = 'FETCH_MINISONGSEARCH_SUCCESS';
export const FETCH_MINISONGSEARCH_ERROR = 'FETCH_MINISONGSEARCH_ERROR';

export const FETCH_MINIARTISTSEARCH_PENDING = 'FETCH_MINIARTISTSEARCH_PENDING';
export const FETCH_MINIARTISTSEARCH_SUCCESS = 'FETCH_MINIARTISTSEARCH_SUCCESS';
export const FETCH_MINIARTISTSEARCH_ERROR = 'FETCH_MINIARTISTSEARCH_ERROR';

export const FETCH_MINIALBUMSEARCH_PENDING = 'FETCH_MINIALBUMSEARCH_PENDING';
export const FETCH_MINIALBUMSEARCH_SUCCESS = 'FETCH_MINIALBUMSEARCH_SUCCESS';
export const FETCH_MINIALBUMSEARCH_ERROR = 'FETCH_MINIALBUMSEARCH_ERROR';

export const FETCH_MINIPLAYLISTSEARCH_PENDING = 'FETCH_MINIPLAYLISTSEARCH_PENDING';
export const FETCH_MINIPLAYLISTSEARCH_SUCCESS = 'FETCH_MINIPLAYLISTSEARCH_SUCCESS';
export const FETCH_MINIPLAYLISTSEARCH_ERROR = 'FETCH_MINIPLAYLISTSEARCH_ERROR';