export const SET_USER = 'SET_USER';
export const SET_CURRENT_TAB = 'SET_CURRENT_TAB';

export const FETCH_ALL_PLAYLISTS_PENDING = 'FETCH_ALL_PLAYLISTS_PENDING';
export const FETCH_ALL_PLAYLISTS_SUCCESS = 'FETCH_ALL_PLAYLISTS_SUCCESS';
export const FETCH_ALL_PLAYLISTS_ERROR = 'FETCH_ALL_PLAYLISTS_ERROR';

export const FETCH_PLAYLIST_PENDING = 'FETCH_PLAYLIST_PENDING';
export const FETCH_PLAYLIST_SUCCESS = 'FETCH_PLAYLIST_SUCCESS';
export const FETCH_PLAYLIST_ERROR = 'FETCH_PLAYLIST_ERROR';
