export const SET_USER = 'SET_USER';
export const SET_CURRENT_TAB = 'SET_CURRENT_TAB';

export const FETCH_ALL_PLAYLISTS_PENDING = 'FETCH_ALL_PLAYLISTS_PENDING';
export const FETCH_ALL_PLAYLISTS_SUCCESS = 'FETCH_ALL_PLAYLISTS_SUCCESS';
export const FETCH_ALL_PLAYLISTS_ERROR = 'FETCH_ALL_PLAYLISTS_ERROR';

export const FETCH_PLAYLIST_PENDING = 'FETCH_PLAYLIST_PENDING';
export const FETCH_PLAYLIST_SUCCESS = 'FETCH_PLAYLIST_SUCCESS';
export const FETCH_PLAYLIST_ERROR = 'FETCH_PLAYLIST_ERROR';

export const SEARCH = 'SEARCH';
export const ADD_SONGS = 'ADD_SONGS';
export const DELETE_SONGS = 'DELETE_SONGS';
export const FETCH_PLAYLIST = 'FETCH_PLAYLIST';
export const CREATE_PLAYLIST = 'CREATE_PLAYLIST';
export const DELETE_PLAYLIST = 'DELETE_PLAYLIST';
